from pyspark.sql import SparkSession
from datetime import datetime, date
import calendar
from dateutil.relativedelta import relativedelta

# Iniciar sessão Spark
spark = SparkSession.builder.getOrCreate()

# Definindo data de processamento e data atual
dt_proc = datetime.now().strftime('%Y%m%d%H%M%S')
current_date = datetime.now().strftime('%Y%m%d')

# Definindo data de processamento do book, data inicial de processamento do book como 12 meses atrás
# e data de processamento em formato string para cálculo das janelas de tempo do book
year, month = datetime.now().year, datetime.now().month
last_day = calendar.monthrange(year, month)[1]
last_day_of_month = date(year, month, last_day)

dt_proc_book = last_day_of_month
dt_ini_proc_book = dt_proc_book - relativedelta(months=12)

dt_proc_book = dt_proc_book.strftime('%Y%m')
dt_ini_proc_book = dt_ini_proc_book.strftime('%Y%m')

dt_proc_book_str = last_day_of_month.strftime('%Y-%m-%d')

dt_proc_book, dt_ini_proc_book, dt_proc_book_str

#--------------------------------- Início Processamento Camada Refined (Stage) ------------------------------------------#

# Lendo dados da pasta data_viz
df_transactions = spark.read.parquet('s3://data-lake-varejo-905418122144/04_refined/data_viz/tb_transactions')
df_transactions.createOrReplaceTempView('tb_transactions')

# Criando variável categórica do dia da compra
tb_dia_compra = spark.sql("""
  select
    invoice_id
    , customer_id
    , date
    , hour
    , discount
    , currency
    , transaction_type
    , payment_method
    , line_total
    , case
        when dayofweek(date) = 1 then 'DOMINGO'
        when dayofweek(date) = 2 then 'SEGUNDA'
        when dayofweek(date) = 3 then 'TERCA'
        when dayofweek(date) = 4 then 'QUARTA'
        when dayofweek(date) = 5 then 'QUINTA'
        when dayofweek(date) = 6 then 'SEXTA'
        when dayofweek(date) = 7 then 'SABADO'
      else null
    end fbc_dia_compra
  from tb_transactions
""")
tb_dia_compra.createOrReplaceTempView('tb_dia_compra')

# Criando variável categórica do período da compra
tb_periodo_compra = spark.sql("""
  select
    *
    , case
        when hour <= 6 then 'MADRUGADA'
        when hour <= 12 then 'MANHA'
        when hour <= 18 then 'TARDE'
        when hour <= 24 then 'NOITE'
      else null
    end fbc_periodo_compra
  from tb_dia_compra
""")
tb_periodo_compra.createOrReplaceTempView('tb_periodo_compra')

# Criando variável categórica do método de pagamento
tb_metodo_pagamento = spark.sql("""
  select
    *
    , case
        when payment_method = 'Cash' then 'DINHEIRO'
        when payment_method = 'Credit Card' then 'CARTAO'
      else null
    end fbc_metodo_pagamento
  from tb_periodo_compra
""")
tb_metodo_pagamento.createOrReplaceTempView('tb_metodo_pagamento')

# Criando variável categórica da moeda
tb_moeda = spark.sql("""
  select
    *
    , case
        when currency = 'USD' then 'DOLAR'
        when currency = 'EUR' then 'EURO'
        when currency = 'GBP' then 'LIBRA'
        when currency = 'CNY' then 'YUAN'
      else null
    end fbc_moeda
  from tb_metodo_pagamento
""")
tb_moeda.createOrReplaceTempView('tb_moeda')

# Criando flags de desconto e retorno
tb_flags = spark.sql("""
  select
    *
    , case
        when discount > 0 then 1
      else 0
    end flg_desconto
    , case
        when transaction_type = 'Return' then 1
        else 0
      end flg_retorno
  from tb_moeda
""")
tb_flags.createOrReplaceTempView('tb_flags')

# Criando variável numérica de quantidade de transações
tb_qtd_transacoes = spark.sql("""
  select
    row_number() over(partition by invoice_id order by customer_id nulls last) as rn
    , *
  from tb_flags
""")
tb_qtd_transacoes.createOrReplaceTempView('tb_qtd_transacoes')

# Organizando dados para a camada stage
stage = spark.sql(f"""
  select
    customer_id
    , {dt_proc} as dt_proc
    , {dt_proc_book} as ref
    , date
    , fbc_dia_compra
    , fbc_periodo_compra
    , fbc_metodo_pagamento
    , fbc_moeda
    , flg_desconto
    , flg_retorno
    , line_total as fvl_invoice_total
    , case when rn = 1 then 1 else null end fvl_qtd_transacoes
    , 1 as fvl_qtd_itens_transacao
  from tb_qtd_transacoes
""")
stage.createOrReplaceTempView('stage')

# Conferindo quantidade de registros
qtd_registros = stage.count()
qtd_registros

# Salvando stage na camada refined em formato parquet
stage.write.mode('append').partitionBy('ref').parquet('s3://data-lake-varejo-905418122144/04_refined/stage')

#----------------------------------- Início Carregamento Base Controle Stage --------------------------------------------#

# Criando dados de controle
df_controle_stage = spark.sql(f"""
    select
        'tb_refined_stage' as tb_name
        , {dt_proc} as dt_proc
        , {qtd_registros} as qtd_registros
""")

# Salvando dados de controle na camada refined em formato parquet
df_controle_stage.write.mode('append').parquet('s3://data-lake-varejo-905418122144/05_controle/refined/')

#---------------------------------- Início Processamento Camada Refined (Book) ------------------------------------------#

# Criando janelas de tempo do book
janelas_tempo = spark.sql(f"""
  select
    *
    , (case when months_between('{dt_proc_book_str}', date) <= 1 then 1 else 0 end) flg_u1m
    , (case when months_between('{dt_proc_book_str}', date) <= 3 then 1 else 0 end) flg_u3m
    , (case when months_between('{dt_proc_book_str}', date) <= 6 then 1 else 0 end) flg_u6m
    , (case when months_between('{dt_proc_book_str}', date) <= 9 then 1 else 0 end) flg_u9m
    , (case when months_between('{dt_proc_book_str}', date) <= 12 then 1 else 0 end) flg_u12m
  from stage
""")
janelas_tempo.createOrReplaceTempView('janelas_tempo')

# # Automatizando a geração de variáveis
# fbc_1 = ['DOMINGO', 'SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO']
# fbc_2 = ['MADRUGADA', 'MANHA', 'TARDE', 'NOITE']
# fbc_3 = ['DINHEIRO', 'CARTAO']
# fbc_4 = ['DOLAR', 'EURO', 'LIBRA', 'YUAN']

# fbcs = {
#   'FBC_DIA_COMPRA': fbc_1,
#   'FBC_PERIODO_COMPRA':fbc_2,
#   'FBC_METODO_PAGAMENTO': fbc_3,
#   'FBC_MOEDA': fbc_4
# }

# fvls_e_flgs = ['FVL_INVOICE_TOTAL','FVL_QTD_TRANSACOES','FVL_QTD_ITENS_TRANSACAO','FLG_DESCONTO','FLG_RETORNO']
# janelas = ['FLG_U1M', 'FLG_U3M', 'FLG_U6M', 'FLG_U9M', 'FLG_U12M']
# aggs = ['SUM', 'AVG', 'MIN', 'MAX']
# count = 0

# for nome_fbc,fbc in fbcs.items():
#   for fbc in fbc:
#     for fvl in fvls_e_flgs:
#       for janela in janelas:
#         for agg in aggs:
#             if (fvl == 'FVL_QTD_TRANSACOES' and agg != 'SUM') or (fvl == 'FVL_QTD_ITENS_TRANSACAO' and agg != 'SUM') or (fvl == 'FLG_DESCONTO' and agg != 'SUM') or (fvl == 'FLG_RETORNO' and agg != 'SUM'):
#                 continue
#             else:
#                 print(f'{agg}(CASE WHEN {nome_fbc} = "{fbc}" AND {janela} = 1 THEN {fvl} END) as VAR_{count},')
#                 count += 1

book = spark.sql("""
  select
    customer_id,
    ref,
    SUM(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_0,
AVG(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_1,
MIN(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_2,
MAX(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_3,
SUM(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_4,
AVG(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_5,
MIN(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_6,
MAX(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_7,
SUM(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_8,
AVG(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_9,
MIN(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_10,
MAX(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_11,
SUM(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_12,
AVG(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_13,
MIN(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_14,
MAX(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_15,
SUM(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_16,
AVG(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_17,
MIN(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_18,
MAX(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_19,
SUM(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U1M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_20,
SUM(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U3M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_21,
SUM(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U6M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_22,
SUM(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U9M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_23,
SUM(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U12M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_24,
SUM(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U1M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_25,
SUM(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U3M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_26,
SUM(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U6M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_27,
SUM(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U9M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_28,
SUM(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U12M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_29,
SUM(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U1M = 1 THEN FLG_DESCONTO END) as VAR_30,
SUM(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U3M = 1 THEN FLG_DESCONTO END) as VAR_31,
SUM(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U6M = 1 THEN FLG_DESCONTO END) as VAR_32,
SUM(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U9M = 1 THEN FLG_DESCONTO END) as VAR_33,
SUM(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U12M = 1 THEN FLG_DESCONTO END) as VAR_34,
SUM(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U1M = 1 THEN FLG_RETORNO END) as VAR_35,
SUM(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U3M = 1 THEN FLG_RETORNO END) as VAR_36,
SUM(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U6M = 1 THEN FLG_RETORNO END) as VAR_37,
SUM(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U9M = 1 THEN FLG_RETORNO END) as VAR_38,
SUM(CASE WHEN FBC_DIA_COMPRA = "DOMINGO" AND FLG_U12M = 1 THEN FLG_RETORNO END) as VAR_39,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_40,
AVG(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_41,
MIN(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_42,
MAX(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_43,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_44,
AVG(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_45,
MIN(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_46,
MAX(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_47,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_48,
AVG(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_49,
MIN(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_50,
MAX(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_51,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_52,
AVG(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_53,
MIN(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_54,
MAX(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_55,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_56,
AVG(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_57,
MIN(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_58,
MAX(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_59,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U1M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_60,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U3M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_61,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U6M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_62,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U9M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_63,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U12M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_64,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U1M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_65,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U3M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_66,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U6M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_67,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U9M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_68,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U12M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_69,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U1M = 1 THEN FLG_DESCONTO END) as VAR_70,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U3M = 1 THEN FLG_DESCONTO END) as VAR_71,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U6M = 1 THEN FLG_DESCONTO END) as VAR_72,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U9M = 1 THEN FLG_DESCONTO END) as VAR_73,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U12M = 1 THEN FLG_DESCONTO END) as VAR_74,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U1M = 1 THEN FLG_RETORNO END) as VAR_75,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U3M = 1 THEN FLG_RETORNO END) as VAR_76,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U6M = 1 THEN FLG_RETORNO END) as VAR_77,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U9M = 1 THEN FLG_RETORNO END) as VAR_78,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEGUNDA" AND FLG_U12M = 1 THEN FLG_RETORNO END) as VAR_79,
SUM(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_80,
AVG(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_81,
MIN(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_82,
MAX(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_83,
SUM(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_84,
AVG(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_85,
MIN(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_86,
MAX(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_87,
SUM(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_88,
AVG(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_89,
MIN(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_90,
MAX(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_91,
SUM(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_92,
AVG(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_93,
MIN(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_94,
MAX(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_95,
SUM(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_96,
AVG(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_97,
MIN(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_98,
MAX(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_99,
SUM(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U1M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_100,
SUM(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U3M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_101,
SUM(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U6M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_102,
SUM(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U9M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_103,
SUM(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U12M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_104,
SUM(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U1M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_105,
SUM(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U3M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_106,
SUM(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U6M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_107,
SUM(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U9M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_108,
SUM(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U12M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_109,
SUM(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U1M = 1 THEN FLG_DESCONTO END) as VAR_110,
SUM(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U3M = 1 THEN FLG_DESCONTO END) as VAR_111,
SUM(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U6M = 1 THEN FLG_DESCONTO END) as VAR_112,
SUM(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U9M = 1 THEN FLG_DESCONTO END) as VAR_113,
SUM(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U12M = 1 THEN FLG_DESCONTO END) as VAR_114,
SUM(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U1M = 1 THEN FLG_RETORNO END) as VAR_115,
SUM(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U3M = 1 THEN FLG_RETORNO END) as VAR_116,
SUM(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U6M = 1 THEN FLG_RETORNO END) as VAR_117,
SUM(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U9M = 1 THEN FLG_RETORNO END) as VAR_118,
SUM(CASE WHEN FBC_DIA_COMPRA = "TERCA" AND FLG_U12M = 1 THEN FLG_RETORNO END) as VAR_119,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_120,
AVG(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_121,
MIN(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_122,
MAX(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_123,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_124,
AVG(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_125,
MIN(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_126,
MAX(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_127,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_128,
AVG(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_129,
MIN(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_130,
MAX(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_131,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_132,
AVG(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_133,
MIN(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_134,
MAX(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_135,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_136,
AVG(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_137,
MIN(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_138,
MAX(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_139,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U1M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_140,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U3M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_141,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U6M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_142,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U9M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_143,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U12M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_144,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U1M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_145,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U3M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_146,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U6M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_147,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U9M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_148,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U12M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_149,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U1M = 1 THEN FLG_DESCONTO END) as VAR_150,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U3M = 1 THEN FLG_DESCONTO END) as VAR_151,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U6M = 1 THEN FLG_DESCONTO END) as VAR_152,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U9M = 1 THEN FLG_DESCONTO END) as VAR_153,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U12M = 1 THEN FLG_DESCONTO END) as VAR_154,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U1M = 1 THEN FLG_RETORNO END) as VAR_155,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U3M = 1 THEN FLG_RETORNO END) as VAR_156,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U6M = 1 THEN FLG_RETORNO END) as VAR_157,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U9M = 1 THEN FLG_RETORNO END) as VAR_158,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUARTA" AND FLG_U12M = 1 THEN FLG_RETORNO END) as VAR_159,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_160,
AVG(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_161,
MIN(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_162,
MAX(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_163,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_164,
AVG(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_165,
MIN(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_166,
MAX(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_167,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_168,
AVG(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_169,
MIN(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_170,
MAX(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_171,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_172,
AVG(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_173,
MIN(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_174,
MAX(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_175,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_176,
AVG(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_177,
MIN(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_178,
MAX(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_179,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U1M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_180,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U3M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_181,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U6M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_182,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U9M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_183,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U12M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_184,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U1M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_185,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U3M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_186,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U6M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_187,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U9M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_188,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U12M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_189,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U1M = 1 THEN FLG_DESCONTO END) as VAR_190,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U3M = 1 THEN FLG_DESCONTO END) as VAR_191,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U6M = 1 THEN FLG_DESCONTO END) as VAR_192,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U9M = 1 THEN FLG_DESCONTO END) as VAR_193,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U12M = 1 THEN FLG_DESCONTO END) as VAR_194,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U1M = 1 THEN FLG_RETORNO END) as VAR_195,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U3M = 1 THEN FLG_RETORNO END) as VAR_196,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U6M = 1 THEN FLG_RETORNO END) as VAR_197,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U9M = 1 THEN FLG_RETORNO END) as VAR_198,
SUM(CASE WHEN FBC_DIA_COMPRA = "QUINTA" AND FLG_U12M = 1 THEN FLG_RETORNO END) as VAR_199,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_200,
AVG(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_201,
MIN(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_202,
MAX(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_203,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_204,
AVG(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_205,
MIN(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_206,
MAX(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_207,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_208,
AVG(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_209,
MIN(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_210,
MAX(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_211,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_212,
AVG(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_213,
MIN(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_214,
MAX(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_215,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_216,
AVG(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_217,
MIN(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_218,
MAX(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_219,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U1M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_220,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U3M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_221,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U6M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_222,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U9M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_223,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U12M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_224,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U1M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_225,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U3M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_226,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U6M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_227,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U9M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_228,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U12M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_229,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U1M = 1 THEN FLG_DESCONTO END) as VAR_230,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U3M = 1 THEN FLG_DESCONTO END) as VAR_231,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U6M = 1 THEN FLG_DESCONTO END) as VAR_232,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U9M = 1 THEN FLG_DESCONTO END) as VAR_233,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U12M = 1 THEN FLG_DESCONTO END) as VAR_234,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U1M = 1 THEN FLG_RETORNO END) as VAR_235,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U3M = 1 THEN FLG_RETORNO END) as VAR_236,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U6M = 1 THEN FLG_RETORNO END) as VAR_237,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U9M = 1 THEN FLG_RETORNO END) as VAR_238,
SUM(CASE WHEN FBC_DIA_COMPRA = "SEXTA" AND FLG_U12M = 1 THEN FLG_RETORNO END) as VAR_239,
SUM(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_240,
AVG(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_241,
MIN(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_242,
MAX(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_243,
SUM(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_244,
AVG(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_245,
MIN(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_246,
MAX(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_247,
SUM(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_248,
AVG(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_249,
MIN(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_250,
MAX(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_251,
SUM(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_252,
AVG(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_253,
MIN(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_254,
MAX(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_255,
SUM(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_256,
AVG(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_257,
MIN(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_258,
MAX(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_259,
SUM(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U1M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_260,
SUM(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U3M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_261,
SUM(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U6M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_262,
SUM(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U9M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_263,
SUM(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U12M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_264,
SUM(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U1M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_265,
SUM(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U3M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_266,
SUM(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U6M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_267,
SUM(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U9M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_268,
SUM(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U12M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_269,
SUM(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U1M = 1 THEN FLG_DESCONTO END) as VAR_270,
SUM(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U3M = 1 THEN FLG_DESCONTO END) as VAR_271,
SUM(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U6M = 1 THEN FLG_DESCONTO END) as VAR_272,
SUM(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U9M = 1 THEN FLG_DESCONTO END) as VAR_273,
SUM(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U12M = 1 THEN FLG_DESCONTO END) as VAR_274,
SUM(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U1M = 1 THEN FLG_RETORNO END) as VAR_275,
SUM(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U3M = 1 THEN FLG_RETORNO END) as VAR_276,
SUM(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U6M = 1 THEN FLG_RETORNO END) as VAR_277,
SUM(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U9M = 1 THEN FLG_RETORNO END) as VAR_278,
SUM(CASE WHEN FBC_DIA_COMPRA = "SABADO" AND FLG_U12M = 1 THEN FLG_RETORNO END) as VAR_279,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_280,
AVG(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_281,
MIN(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_282,
MAX(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_283,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_284,
AVG(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_285,
MIN(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_286,
MAX(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_287,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_288,
AVG(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_289,
MIN(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_290,
MAX(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_291,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_292,
AVG(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_293,
MIN(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_294,
MAX(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_295,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_296,
AVG(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_297,
MIN(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_298,
MAX(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_299,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U1M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_300,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U3M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_301,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U6M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_302,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U9M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_303,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U12M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_304,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U1M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_305,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U3M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_306,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U6M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_307,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U9M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_308,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U12M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_309,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U1M = 1 THEN FLG_DESCONTO END) as VAR_310,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U3M = 1 THEN FLG_DESCONTO END) as VAR_311,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U6M = 1 THEN FLG_DESCONTO END) as VAR_312,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U9M = 1 THEN FLG_DESCONTO END) as VAR_313,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U12M = 1 THEN FLG_DESCONTO END) as VAR_314,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U1M = 1 THEN FLG_RETORNO END) as VAR_315,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U3M = 1 THEN FLG_RETORNO END) as VAR_316,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U6M = 1 THEN FLG_RETORNO END) as VAR_317,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U9M = 1 THEN FLG_RETORNO END) as VAR_318,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MADRUGADA" AND FLG_U12M = 1 THEN FLG_RETORNO END) as VAR_319,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_320,
AVG(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_321,
MIN(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_322,
MAX(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_323,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_324,
AVG(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_325,
MIN(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_326,
MAX(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_327,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_328,
AVG(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_329,
MIN(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_330,
MAX(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_331,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_332,
AVG(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_333,
MIN(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_334,
MAX(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_335,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_336,
AVG(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_337,
MIN(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_338,
MAX(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_339,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U1M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_340,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U3M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_341,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U6M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_342,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U9M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_343,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U12M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_344,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U1M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_345,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U3M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_346,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U6M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_347,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U9M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_348,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U12M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_349,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U1M = 1 THEN FLG_DESCONTO END) as VAR_350,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U3M = 1 THEN FLG_DESCONTO END) as VAR_351,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U6M = 1 THEN FLG_DESCONTO END) as VAR_352,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U9M = 1 THEN FLG_DESCONTO END) as VAR_353,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U12M = 1 THEN FLG_DESCONTO END) as VAR_354,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U1M = 1 THEN FLG_RETORNO END) as VAR_355,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U3M = 1 THEN FLG_RETORNO END) as VAR_356,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U6M = 1 THEN FLG_RETORNO END) as VAR_357,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U9M = 1 THEN FLG_RETORNO END) as VAR_358,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "MANHA" AND FLG_U12M = 1 THEN FLG_RETORNO END) as VAR_359,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_360,
AVG(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_361,
MIN(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_362,
MAX(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_363,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_364,
AVG(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_365,
MIN(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_366,
MAX(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_367,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_368,
AVG(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_369,
MIN(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_370,
MAX(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_371,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_372,
AVG(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_373,
MIN(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_374,
MAX(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_375,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_376,
AVG(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_377,
MIN(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_378,
MAX(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_379,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U1M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_380,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U3M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_381,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U6M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_382,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U9M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_383,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U12M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_384,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U1M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_385,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U3M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_386,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U6M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_387,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U9M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_388,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U12M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_389,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U1M = 1 THEN FLG_DESCONTO END) as VAR_390,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U3M = 1 THEN FLG_DESCONTO END) as VAR_391,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U6M = 1 THEN FLG_DESCONTO END) as VAR_392,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U9M = 1 THEN FLG_DESCONTO END) as VAR_393,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U12M = 1 THEN FLG_DESCONTO END) as VAR_394,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U1M = 1 THEN FLG_RETORNO END) as VAR_395,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U3M = 1 THEN FLG_RETORNO END) as VAR_396,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U6M = 1 THEN FLG_RETORNO END) as VAR_397,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U9M = 1 THEN FLG_RETORNO END) as VAR_398,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "TARDE" AND FLG_U12M = 1 THEN FLG_RETORNO END) as VAR_399,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_400,
AVG(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_401,
MIN(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_402,
MAX(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_403,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_404,
AVG(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_405,
MIN(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_406,
MAX(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_407,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_408,
AVG(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_409,
MIN(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_410,
MAX(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_411,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_412,
AVG(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_413,
MIN(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_414,
MAX(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_415,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_416,
AVG(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_417,
MIN(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_418,
MAX(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_419,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U1M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_420,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U3M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_421,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U6M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_422,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U9M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_423,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U12M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_424,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U1M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_425,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U3M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_426,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U6M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_427,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U9M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_428,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U12M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_429,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U1M = 1 THEN FLG_DESCONTO END) as VAR_430,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U3M = 1 THEN FLG_DESCONTO END) as VAR_431,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U6M = 1 THEN FLG_DESCONTO END) as VAR_432,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U9M = 1 THEN FLG_DESCONTO END) as VAR_433,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U12M = 1 THEN FLG_DESCONTO END) as VAR_434,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U1M = 1 THEN FLG_RETORNO END) as VAR_435,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U3M = 1 THEN FLG_RETORNO END) as VAR_436,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U6M = 1 THEN FLG_RETORNO END) as VAR_437,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U9M = 1 THEN FLG_RETORNO END) as VAR_438,
SUM(CASE WHEN FBC_PERIODO_COMPRA = "NOITE" AND FLG_U12M = 1 THEN FLG_RETORNO END) as VAR_439,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_440,
AVG(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_441,
MIN(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_442,
MAX(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_443,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_444,
AVG(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_445,
MIN(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_446,
MAX(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_447,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_448,
AVG(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_449,
MIN(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_450,
MAX(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_451,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_452,
AVG(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_453,
MIN(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_454,
MAX(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_455,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_456,
AVG(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_457,
MIN(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_458,
MAX(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_459,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U1M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_460,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U3M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_461,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U6M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_462,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U9M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_463,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U12M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_464,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U1M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_465,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U3M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_466,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U6M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_467,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U9M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_468,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U12M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_469,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U1M = 1 THEN FLG_DESCONTO END) as VAR_470,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U3M = 1 THEN FLG_DESCONTO END) as VAR_471,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U6M = 1 THEN FLG_DESCONTO END) as VAR_472,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U9M = 1 THEN FLG_DESCONTO END) as VAR_473,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U12M = 1 THEN FLG_DESCONTO END) as VAR_474,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U1M = 1 THEN FLG_RETORNO END) as VAR_475,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U3M = 1 THEN FLG_RETORNO END) as VAR_476,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U6M = 1 THEN FLG_RETORNO END) as VAR_477,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U9M = 1 THEN FLG_RETORNO END) as VAR_478,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "DINHEIRO" AND FLG_U12M = 1 THEN FLG_RETORNO END) as VAR_479,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_480,
AVG(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_481,
MIN(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_482,
MAX(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_483,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_484,
AVG(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_485,
MIN(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_486,
MAX(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_487,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_488,
AVG(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_489,
MIN(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_490,
MAX(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_491,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_492,
AVG(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_493,
MIN(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_494,
MAX(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_495,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_496,
AVG(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_497,
MIN(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_498,
MAX(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_499,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U1M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_500,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U3M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_501,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U6M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_502,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U9M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_503,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U12M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_504,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U1M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_505,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U3M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_506,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U6M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_507,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U9M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_508,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U12M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_509,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U1M = 1 THEN FLG_DESCONTO END) as VAR_510,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U3M = 1 THEN FLG_DESCONTO END) as VAR_511,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U6M = 1 THEN FLG_DESCONTO END) as VAR_512,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U9M = 1 THEN FLG_DESCONTO END) as VAR_513,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U12M = 1 THEN FLG_DESCONTO END) as VAR_514,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U1M = 1 THEN FLG_RETORNO END) as VAR_515,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U3M = 1 THEN FLG_RETORNO END) as VAR_516,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U6M = 1 THEN FLG_RETORNO END) as VAR_517,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U9M = 1 THEN FLG_RETORNO END) as VAR_518,
SUM(CASE WHEN FBC_METODO_PAGAMENTO = "CARTAO" AND FLG_U12M = 1 THEN FLG_RETORNO END) as VAR_519,
SUM(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_520,
AVG(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_521,
MIN(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_522,
MAX(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_523,
SUM(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_524,
AVG(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_525,
MIN(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_526,
MAX(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_527,
SUM(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_528,
AVG(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_529,
MIN(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_530,
MAX(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_531,
SUM(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_532,
AVG(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_533,
MIN(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_534,
MAX(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_535,
SUM(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_536,
AVG(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_537,
MIN(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_538,
MAX(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_539,
SUM(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U1M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_540,
SUM(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U3M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_541,
SUM(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U6M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_542,
SUM(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U9M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_543,
SUM(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U12M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_544,
SUM(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U1M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_545,
SUM(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U3M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_546,
SUM(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U6M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_547,
SUM(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U9M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_548,
SUM(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U12M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_549,
SUM(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U1M = 1 THEN FLG_DESCONTO END) as VAR_550,
SUM(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U3M = 1 THEN FLG_DESCONTO END) as VAR_551,
SUM(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U6M = 1 THEN FLG_DESCONTO END) as VAR_552,
SUM(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U9M = 1 THEN FLG_DESCONTO END) as VAR_553,
SUM(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U12M = 1 THEN FLG_DESCONTO END) as VAR_554,
SUM(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U1M = 1 THEN FLG_RETORNO END) as VAR_555,
SUM(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U3M = 1 THEN FLG_RETORNO END) as VAR_556,
SUM(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U6M = 1 THEN FLG_RETORNO END) as VAR_557,
SUM(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U9M = 1 THEN FLG_RETORNO END) as VAR_558,
SUM(CASE WHEN FBC_MOEDA = "DOLAR" AND FLG_U12M = 1 THEN FLG_RETORNO END) as VAR_559,
SUM(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_560,
AVG(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_561,
MIN(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_562,
MAX(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_563,
SUM(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_564,
AVG(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_565,
MIN(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_566,
MAX(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_567,
SUM(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_568,
AVG(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_569,
MIN(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_570,
MAX(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_571,
SUM(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_572,
AVG(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_573,
MIN(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_574,
MAX(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_575,
SUM(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_576,
AVG(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_577,
MIN(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_578,
MAX(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_579,
SUM(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U1M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_580,
SUM(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U3M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_581,
SUM(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U6M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_582,
SUM(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U9M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_583,
SUM(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U12M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_584,
SUM(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U1M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_585,
SUM(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U3M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_586,
SUM(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U6M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_587,
SUM(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U9M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_588,
SUM(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U12M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_589,
SUM(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U1M = 1 THEN FLG_DESCONTO END) as VAR_590,
SUM(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U3M = 1 THEN FLG_DESCONTO END) as VAR_591,
SUM(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U6M = 1 THEN FLG_DESCONTO END) as VAR_592,
SUM(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U9M = 1 THEN FLG_DESCONTO END) as VAR_593,
SUM(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U12M = 1 THEN FLG_DESCONTO END) as VAR_594,
SUM(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U1M = 1 THEN FLG_RETORNO END) as VAR_595,
SUM(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U3M = 1 THEN FLG_RETORNO END) as VAR_596,
SUM(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U6M = 1 THEN FLG_RETORNO END) as VAR_597,
SUM(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U9M = 1 THEN FLG_RETORNO END) as VAR_598,
SUM(CASE WHEN FBC_MOEDA = "EURO" AND FLG_U12M = 1 THEN FLG_RETORNO END) as VAR_599,
SUM(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_600,
AVG(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_601,
MIN(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_602,
MAX(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_603,
SUM(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_604,
AVG(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_605,
MIN(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_606,
MAX(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_607,
SUM(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_608,
AVG(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_609,
MIN(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_610,
MAX(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_611,
SUM(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_612,
AVG(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_613,
MIN(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_614,
MAX(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_615,
SUM(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_616,
AVG(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_617,
MIN(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_618,
MAX(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_619,
SUM(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U1M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_620,
SUM(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U3M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_621,
SUM(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U6M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_622,
SUM(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U9M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_623,
SUM(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U12M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_624,
SUM(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U1M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_625,
SUM(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U3M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_626,
SUM(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U6M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_627,
SUM(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U9M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_628,
SUM(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U12M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_629,
SUM(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U1M = 1 THEN FLG_DESCONTO END) as VAR_630,
SUM(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U3M = 1 THEN FLG_DESCONTO END) as VAR_631,
SUM(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U6M = 1 THEN FLG_DESCONTO END) as VAR_632,
SUM(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U9M = 1 THEN FLG_DESCONTO END) as VAR_633,
SUM(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U12M = 1 THEN FLG_DESCONTO END) as VAR_634,
SUM(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U1M = 1 THEN FLG_RETORNO END) as VAR_635,
SUM(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U3M = 1 THEN FLG_RETORNO END) as VAR_636,
SUM(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U6M = 1 THEN FLG_RETORNO END) as VAR_637,
SUM(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U9M = 1 THEN FLG_RETORNO END) as VAR_638,
SUM(CASE WHEN FBC_MOEDA = "LIBRA" AND FLG_U12M = 1 THEN FLG_RETORNO END) as VAR_639,
SUM(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_640,
AVG(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_641,
MIN(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_642,
MAX(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U1M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_643,
SUM(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_644,
AVG(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_645,
MIN(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_646,
MAX(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U3M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_647,
SUM(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_648,
AVG(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_649,
MIN(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_650,
MAX(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U6M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_651,
SUM(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_652,
AVG(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_653,
MIN(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_654,
MAX(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U9M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_655,
SUM(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_656,
AVG(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_657,
MIN(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_658,
MAX(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U12M = 1 THEN FVL_INVOICE_TOTAL END) as VAR_659,
SUM(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U1M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_660,
SUM(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U3M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_661,
SUM(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U6M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_662,
SUM(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U9M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_663,
SUM(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U12M = 1 THEN FVL_QTD_TRANSACOES END) as VAR_664,
SUM(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U1M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_665,
SUM(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U3M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_666,
SUM(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U6M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_667,
SUM(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U9M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_668,
SUM(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U12M = 1 THEN FVL_QTD_ITENS_TRANSACAO END) as VAR_669,
SUM(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U1M = 1 THEN FLG_DESCONTO END) as VAR_670,
SUM(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U3M = 1 THEN FLG_DESCONTO END) as VAR_671,
SUM(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U6M = 1 THEN FLG_DESCONTO END) as VAR_672,
SUM(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U9M = 1 THEN FLG_DESCONTO END) as VAR_673,
SUM(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U12M = 1 THEN FLG_DESCONTO END) as VAR_674,
SUM(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U1M = 1 THEN FLG_RETORNO END) as VAR_675,
SUM(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U3M = 1 THEN FLG_RETORNO END) as VAR_676,
SUM(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U6M = 1 THEN FLG_RETORNO END) as VAR_677,
SUM(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U9M = 1 THEN FLG_RETORNO END) as VAR_678,
SUM(CASE WHEN FBC_MOEDA = "YUAN" AND FLG_U12M = 1 THEN FLG_RETORNO END) as VAR_679
    from janelas_tempo
  group by 1,2
""")

# Salvando book na camada refined em formato parquet
book.write.mode('append').partitionBy('ref').parquet('s3://data-lake-varejo-905418122144/04_refined/book')

#--------------------------------------- Início Carregamento Base Controle Book -------------------------------------------#

# Conferindo quantidade de registros
qtd_registros_book = book.count()

# Criando dados de controle
df_controle_book = spark.sql(f"""
    select
        'tb_refined_book' as tb_name
        , {dt_proc} as dt_proc
        , {qtd_registros_book} as qtd_registros
""")

# Salvando dados de controle na camada refined em formato parquet
df_controle_book.write.mode('append').parquet('s3://data-lake-varejo-905418122144/05_controle/refined/')